---
- name: register dotdeb key
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg state=present

- name: add dotdeb default repositories
  apt_repository: repo='deb http://packages.dotdeb.org {{ debian.version }} all' state=present

- name: add dotdeb php55 repositories
  apt_repository: repo='deb http://packages.dotdeb.org {{ debian.version }}-php55 all' state=present

- name: add dotdeb php55 sources repositories
  apt_repository: repo='deb-src http://packages.dotdeb.org {{ debian.version }}-php55 all' state=present

- name: register sury key
  apt_key: url=https://packages.sury.org/php/apt.gpg state=present

- name: add sury default repositories
  apt_repository: repo='deb https://packages.sury.org/php/ {{ debian.version }} main' state=present

- name: install xdebug php packages
  apt:
    name: {{ packages }}
    state: latest
    update_cache: yes
    force: yes
  vars:
    packages:
      - php5-xdebug

- name: copy xdebug.ini
  template: src=xdebug.ini.j2 dest=/etc/php5/mods-available/xdebug.ini

- name: activate xdebug
  shell: php5enmod xdebug
